export const BALL_EVENTS = [
  "WICKET",
  "MAIDEN_OVER",
  "FOUR",
  "SIX",
  "FIFTY",
  "HUNDRED",
  "UDRS",
  "PARTNERSHIP",
  "INJURY",
  "TEAM_FIFTY",
  "TEAM_HUNDRED",
  "RUNOUT_MISS",
  "HIGHSCORING_OVER",
  "OVER_BREAK",
] as const;
